[2024-05-12 06:15:00,951:INFO:main:welcome to our custom log]
[2024-05-12 06:17:14,383:INFO:main:welcome to our custom log]
[2024-05-12 16:39:52,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 16:39:52,432: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 16:39:52,442: INFO: common: created directory at: artifacts]
[2024-05-12 16:39:52,444: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-12 16:39:52,445: INFO: 986331348: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-12 16:40:19,579: INFO: 986331348: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-12 17:00:45,698: INFO: main: welcome to our custom log]
[2024-05-12 17:01:40,463:INFO:main:welcome to our custom log]
[2024-05-12 17:02:39,620: INFO: main: welcome to our custom log]
[2024-05-12 18:59:24,382: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-12 18:59:24,405: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 18:59:24,405: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 18:59:24,406: INFO: common: created directory at: artifacts]
[2024-05-12 18:59:24,407: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-12 18:59:24,407: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-12 18:59:51,953: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-12 18:59:53,236: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-12 20:06:05,871: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:06:05,874: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:06:05,875: INFO: common: created directory at: artifacts]
[2024-05-12 20:09:53,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:09:53,905: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:09:53,906: INFO: common: created directory at: artifacts]
[2024-05-12 20:10:28,302: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:10:28,303: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:10:28,305: INFO: common: created directory at: artifacts]
[2024-05-12 20:25:45,970: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:25:45,972: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:25:45,973: INFO: common: created directory at: artifacts]
[2024-05-12 20:56:03,280: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:56:03,281: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:56:03,282: INFO: common: created directory at: artifacts]
[2024-05-12 20:56:09,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 20:56:09,962: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 20:56:09,964: INFO: common: created directory at: artifacts]
[2024-05-12 21:01:20,290: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 21:01:20,292: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 21:01:20,294: INFO: common: created directory at: artifacts]
[2024-05-12 21:03:21,646: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-12 21:03:21,648: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-12 21:03:21,649: INFO: common: created directory at: artifacts]
[2024-05-13 10:04:13,637: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 10:04:15,580: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 10:04:15,635: INFO: common: created directory at: artifacts]
[2024-05-13 10:37:56,531: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 10:37:56,878: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 10:37:56,898: INFO: common: created directory at: artifacts]
[2024-05-13 11:07:24,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 11:07:24,489: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 11:07:24,490: INFO: common: created directory at: artifacts]
[2024-05-13 11:18:47,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 11:18:47,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 11:18:47,436: INFO: common: created directory at: artifacts]
[2024-05-13 11:21:18,757: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 11:21:18,759: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 11:21:18,761: INFO: common: created directory at: artifacts]
[2024-05-13 11:53:20,023: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 11:53:20,321: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 11:53:20,345: INFO: common: created directory at: artifacts]
[2024-05-13 11:55:29,457: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 11:55:29,460: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 11:55:29,462: INFO: common: created directory at: artifacts]
[2024-05-13 12:15:21,758: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:15:21,760: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:15:21,761: INFO: common: created directory at: artifacts]
[2024-05-13 12:50:01,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:50:01,102: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:50:01,104: INFO: common: created directory at: artifacts]
[2024-05-13 12:50:47,947: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:50:47,949: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:50:47,950: INFO: common: created directory at: artifacts]
[2024-05-13 12:52:40,186: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:52:40,189: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:52:40,192: INFO: common: created directory at: artifacts]
[2024-05-13 12:52:50,441: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:52:50,443: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:52:50,445: INFO: common: created directory at: artifacts]
[2024-05-13 12:52:56,549: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 12:52:56,551: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 12:52:56,552: INFO: common: created directory at: artifacts]
[2024-05-13 13:06:52,326: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 13:06:52,328: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 13:06:52,331: INFO: common: created directory at: artifacts]
[2024-05-13 13:42:51,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 13:42:51,851: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 13:42:51,872: INFO: common: created directory at: artifacts]
[2024-05-13 13:53:48,395: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 13:53:48,423: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 13:53:48,428: INFO: common: created directory at: artifacts]
[2024-05-13 14:04:03,424: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 14:04:03,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 14:04:03,436: INFO: common: created directory at: artifacts]
[2024-05-13 15:03:07,151: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 15:03:07,189: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 15:03:07,204: INFO: common: created directory at: artifacts]
[2024-05-13 15:07:26,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 15:07:26,830: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 15:07:26,832: INFO: common: created directory at: artifacts]
[2024-05-13 16:59:43,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 16:59:43,096: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 16:59:43,122: INFO: common: created directory at: artifacts]
[2024-05-13 17:01:26,985: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:01:26,988: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:01:26,990: INFO: common: created directory at: artifacts]
[2024-05-13 17:08:16,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:08:16,037: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:08:16,038: INFO: common: created directory at: artifacts]
[2024-05-13 17:14:37,513: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:14:37,516: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:14:37,517: INFO: common: created directory at: artifacts]
[2024-05-13 17:15:32,220: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:15:32,222: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:15:32,223: INFO: common: created directory at: artifacts]
[2024-05-13 17:21:43,064: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:21:43,066: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:21:43,067: INFO: common: created directory at: artifacts]
[2024-05-13 17:31:59,316: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 17:31:59,324: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 17:31:59,324: INFO: common: created directory at: artifacts]
[2024-05-13 18:01:34,359: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 18:01:36,310: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 18:01:36,362: INFO: common: created directory at: artifacts]
[2024-05-13 18:01:36,362: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-13 18:02:25,557: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 18:02:25,562: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 18:02:25,562: INFO: common: created directory at: artifacts]
[2024-05-13 18:02:25,566: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-13 18:02:54,766: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-13 18:22:32,786: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-13 18:22:32,786: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 18:22:32,794: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 18:22:32,811: INFO: common: created directory at: artifacts]
[2024-05-13 18:22:32,812: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-13 18:22:32,812: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 18:22:58,401: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 18:23:00,456: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-13 18:24:07,282: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-13 18:24:07,282: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 18:24:07,282: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 18:24:07,282: INFO: common: created directory at: artifacts]
[2024-05-13 18:24:07,282: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-13 18:24:07,282: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 18:24:30,560: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 18:24:31,302: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-13 21:15:38,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:15:38,522: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:15:38,558: INFO: common: created directory at: artifacts]
[2024-05-13 21:15:38,563: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-13 21:15:44,504: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-13 21:18:01,481: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-13 21:27:37,316: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-13 21:27:37,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:27:37,332: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:27:37,332: INFO: common: created directory at: artifacts]
[2024-05-13 21:27:37,337: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-13 21:27:37,337: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 21:28:04,683: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 21:28:06,765: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-13 21:31:37,785: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-13 21:31:37,793: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:31:37,793: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:31:37,793: INFO: common: created directory at: artifacts]
[2024-05-13 21:31:37,810: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-13 21:31:37,818: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 21:32:05,017: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-13 21:32:06,046: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-13 21:32:06,046: INFO: main: *******************]
[2024-05-13 21:32:06,046: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-13 21:32:06,046: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:32:06,061: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:32:06,061: INFO: common: created directory at: artifacts]
[2024-05-13 21:32:06,061: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-13 21:32:07,247: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-13 21:32:08,333: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-13 21:46:59,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:47:00,734: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:47:00,770: INFO: common: created directory at: artifacts]
[2024-05-13 21:58:48,179: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 21:58:48,183: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 21:58:48,183: INFO: common: created directory at: artifacts]
[2024-05-13 22:01:30,145: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 22:01:30,439: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 22:01:30,475: INFO: common: created directory at: artifacts]
[2024-05-13 22:46:50,797: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-13 22:46:52,643: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-13 22:46:52,685: INFO: common: created directory at: artifacts]
[2024-05-14 00:16:02,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 00:16:02,699: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 00:16:02,699: INFO: common: created directory at: artifacts]
[2024-05-14 00:20:10,253: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 00:20:10,257: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 00:20:10,259: INFO: common: created directory at: artifacts]
[2024-05-14 11:29:31,307: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:29:31,369: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:29:31,413: INFO: common: created directory at: artifacts]
[2024-05-14 11:31:15,208: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:31:15,216: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:31:15,218: INFO: common: created directory at: artifacts]
[2024-05-14 11:36:44,782: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:36:44,789: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:36:44,792: INFO: common: created directory at: artifacts]
[2024-05-14 11:36:44,795: INFO: common: created directory at: artifacts\training]
[2024-05-14 11:50:30,641: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-14 11:50:30,649: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:50:30,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:50:30,733: INFO: common: created directory at: artifacts]
[2024-05-14 11:50:30,734: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-14 11:50:30,734: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-14 11:51:08,609: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-14 11:51:09,291: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-14 11:51:09,292: INFO: main: *******************]
[2024-05-14 11:51:09,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-14 11:51:09,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:51:09,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:51:09,297: INFO: common: created directory at: artifacts]
[2024-05-14 11:51:09,297: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-14 11:51:10,878: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-14 11:51:11,675: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-14 11:51:11,676: INFO: main: *******************]
[2024-05-14 11:51:11,676: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-14 11:51:11,678: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 11:51:11,679: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 11:51:11,680: INFO: common: created directory at: artifacts]
[2024-05-14 11:51:11,680: INFO: common: created directory at: artifacts\training]
[2024-05-14 11:52:21,048: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-14 15:28:31,444: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 15:28:31,543: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 15:28:31,572: INFO: common: created directory at: artifacts]
[2024-05-14 15:28:58,524: INFO: common: json file saved at: scores.json]
[2024-05-14 15:31:08,419: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 15:31:08,426: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 15:31:08,428: INFO: common: created directory at: artifacts]
[2024-05-14 15:31:32,952: INFO: common: json file saved at: scores.json]
[2024-05-14 15:43:42,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 15:43:42,383: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 15:43:42,410: INFO: common: created directory at: artifacts]
[2024-05-14 15:44:05,551: INFO: common: json file saved at: scores.json]
[2024-05-14 18:11:49,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 18:11:49,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 18:11:49,781: INFO: common: created directory at: artifacts]
[2024-05-14 18:12:16,334: INFO: common: json file saved at: scores.json]
[2024-05-14 18:12:24,318: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-14 18:12:26,331: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmpy2ohl5nq\model\data\model\assets]
[2024-05-14 18:16:46,331: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /jyotir2003/Kidney-Disease-Classification-Deep-Learning-Project.mlflow/api/2.0/mlflow-artifacts/artifacts/771d8ca40a1241b888ba338b5520d2cb/7c2de90993744ae283307c76814e5d9f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-14 18:16:50,490: WARNING: connectionpool: Retrying (Retry(total=3, connect=4, read=4, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019922E4C400>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /jyotir2003/Kidney-Disease-Classification-Deep-Learning-Project.mlflow/api/2.0/mlflow-artifacts/artifacts/771d8ca40a1241b888ba338b5520d2cb/7c2de90993744ae283307c76814e5d9f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-14 18:16:58,554: WARNING: connectionpool: Retrying (Retry(total=2, connect=3, read=4, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019922E4CBB0>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /jyotir2003/Kidney-Disease-Classification-Deep-Learning-Project.mlflow/api/2.0/mlflow-artifacts/artifacts/771d8ca40a1241b888ba338b5520d2cb/7c2de90993744ae283307c76814e5d9f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-14 18:17:14,898: WARNING: connectionpool: Retrying (Retry(total=1, connect=2, read=4, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000019922E54820>: Failed to resolve 'dagshub.com' ([Errno 11001] getaddrinfo failed)")': /jyotir2003/Kidney-Disease-Classification-Deep-Learning-Project.mlflow/api/2.0/mlflow-artifacts/artifacts/771d8ca40a1241b888ba338b5520d2cb/7c2de90993744ae283307c76814e5d9f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-14 18:45:52,046: WARNING: connectionpool: Retrying (Retry(total=0, connect=2, read=3, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /jyotir2003/Kidney-Disease-Classification-Deep-Learning-Project.mlflow/api/2.0/mlflow-artifacts/artifacts/771d8ca40a1241b888ba338b5520d2cb/7c2de90993744ae283307c76814e5d9f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-05-14 18:46:45,325: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 18:46:45,402: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 18:46:45,463: INFO: common: created directory at: artifacts]
[2024-05-14 18:47:11,517: INFO: common: json file saved at: scores.json]
[2024-05-14 18:47:17,897: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-14 18:47:19,485: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmp8d1aq65y\model\data\model\assets]
[2024-05-14 22:38:55,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 22:38:55,047: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 22:38:55,095: INFO: common: created directory at: artifacts]
[2024-05-14 22:39:32,673: INFO: common: json file saved at: scores.json]
[2024-05-14 22:39:41,070: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-14 22:39:42,728: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmpzuxelgl6\model\data\model\assets]
[2024-05-14 22:46:33,135: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 22:46:33,158: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 22:46:33,176: INFO: common: created directory at: artifacts]
[2024-05-14 22:47:07,330: INFO: common: json file saved at: scores.json]
[2024-05-14 22:47:15,821: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-14 22:47:17,198: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmpgbbrjk3s\model\data\model\assets]
[2024-05-14 23:20:13,373: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-14 23:20:13,401: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 23:20:13,436: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 23:20:13,469: INFO: common: created directory at: artifacts]
[2024-05-14 23:20:13,471: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-14 23:20:13,473: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-14 23:20:42,132: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-14 23:20:44,472: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-14 23:20:44,472: INFO: main: *******************]
[2024-05-14 23:20:44,473: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-14 23:20:44,480: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 23:20:44,483: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 23:20:44,484: INFO: common: created directory at: artifacts]
[2024-05-14 23:20:44,486: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-14 23:20:46,810: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-14 23:20:49,490: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-14 23:20:49,492: INFO: main: *******************]
[2024-05-14 23:20:49,492: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-14 23:20:49,502: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-14 23:20:49,509: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-14 23:20:49,510: INFO: common: created directory at: artifacts]
[2024-05-14 23:20:49,512: INFO: common: created directory at: artifacts\training]
[2024-05-14 23:22:46,674: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-14 23:22:46,716: INFO: main: *******************]
[2024-05-14 23:22:46,717: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-14 23:22:46,718: ERROR: main: name 'EvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "e:\Projects\Kidney_Disease_Classification\main.py", line 45, in <module>
    model_evalution = EvaluationPipeline()
NameError: name 'EvaluationPipeline' is not defined
[2024-05-15 07:25:41,810: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 07:25:41,812: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:25:41,850: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:25:41,866: INFO: common: created directory at: artifacts]
[2024-05-15 07:25:41,866: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 07:25:41,867: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 07:26:09,153: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 07:26:10,278: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 07:26:10,279: INFO: main: *******************]
[2024-05-15 07:26:10,280: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 07:26:10,284: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:26:10,287: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:26:10,288: INFO: common: created directory at: artifacts]
[2024-05-15 07:26:10,289: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 07:26:17,090: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 07:26:22,905: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 07:26:22,906: INFO: main: *******************]
[2024-05-15 07:26:22,906: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 07:26:22,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:26:22,913: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:26:22,914: INFO: common: created directory at: artifacts]
[2024-05-15 07:26:22,932: INFO: common: created directory at: artifacts\training]
[2024-05-15 07:28:07,675: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 07:36:00,260: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:36:00,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:36:00,333: INFO: common: created directory at: artifacts]
[2024-05-15 07:36:28,527: INFO: common: json file saved at: scores.json]
[2024-05-15 07:36:34,377: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-15 07:36:35,862: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmp75cvresj\model\data\model\assets]
[2024-05-15 07:47:33,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:47:33,775: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:47:33,791: INFO: common: created directory at: artifacts]
[2024-05-15 07:48:01,513: INFO: common: json file saved at: scores.json]
[2024-05-15 07:48:06,800: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-15 07:48:08,095: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmpq96_ri35\model\data\model\assets]
[2024-05-15 07:51:11,152: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 07:51:11,155: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:51:11,157: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:51:11,158: INFO: common: created directory at: artifacts]
[2024-05-15 07:51:11,158: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 07:51:11,159: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 07:51:38,350: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 07:51:39,429: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 07:51:39,430: INFO: main: *******************]
[2024-05-15 07:51:39,430: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 07:51:39,432: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:51:39,434: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:51:39,435: INFO: common: created directory at: artifacts]
[2024-05-15 07:51:39,435: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 07:51:40,233: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 07:51:43,182: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 07:51:43,183: INFO: main: *******************]
[2024-05-15 07:51:43,183: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 07:51:43,187: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 07:51:43,190: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 07:51:43,190: INFO: common: created directory at: artifacts]
[2024-05-15 07:51:43,190: INFO: common: created directory at: artifacts\training]
[2024-05-15 07:53:06,752: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 07:53:06,802: INFO: main: *******************]
[2024-05-15 07:53:06,839: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 07:53:06,840: ERROR: main: name 'EvaluationPipeline' is not defined]
Traceback (most recent call last):
  File "e:\Projects\Kidney_Disease_Classification\main.py", line 45, in <module>
    model_evalution = EvaluationPipeline()
NameError: name 'EvaluationPipeline' is not defined
[2024-05-15 08:08:53,469: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 08:08:53,473: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:08:53,504: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:08:53,548: INFO: common: created directory at: artifacts]
[2024-05-15 08:08:53,569: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 08:08:53,570: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 08:09:20,499: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 08:09:21,548: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 08:09:21,550: INFO: main: *******************]
[2024-05-15 08:09:21,550: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 08:09:21,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:09:21,555: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:09:21,556: INFO: common: created directory at: artifacts]
[2024-05-15 08:09:21,556: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 08:09:24,616: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 08:09:26,699: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 08:09:26,699: INFO: main: *******************]
[2024-05-15 08:09:26,699: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 08:09:26,701: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:09:26,703: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:09:26,703: INFO: common: created directory at: artifacts]
[2024-05-15 08:09:26,711: INFO: common: created directory at: artifacts\training]
[2024-05-15 08:10:46,000: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 08:10:46,015: INFO: main: *******************]
[2024-05-15 08:10:46,015: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 08:10:46,019: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:10:46,254: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:10:46,297: INFO: common: created directory at: artifacts]
[2024-05-15 08:11:08,659: INFO: common: json file saved at: scores.json]
[2024-05-15 08:11:08,660: INFO: common: json file saved at: scores.json]
[2024-05-15 08:11:08,661: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-15 08:15:35,966: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 08:15:35,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:15:35,969: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:15:35,970: INFO: common: created directory at: artifacts]
[2024-05-15 08:15:35,989: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 08:15:35,990: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 08:16:02,475: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 08:16:03,287: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 08:16:03,288: INFO: main: *******************]
[2024-05-15 08:16:03,288: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 08:16:03,291: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:16:03,293: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:16:03,293: INFO: common: created directory at: artifacts]
[2024-05-15 08:16:03,294: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 08:16:06,143: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 08:16:07,244: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 08:16:07,244: INFO: main: *******************]
[2024-05-15 08:16:07,245: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 08:16:07,247: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:16:07,251: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:16:07,251: INFO: common: created directory at: artifacts]
[2024-05-15 08:16:07,252: INFO: common: created directory at: artifacts\training]
[2024-05-15 08:17:20,796: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 08:17:20,796: INFO: main: *******************]
[2024-05-15 08:17:20,797: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 08:17:20,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 08:17:20,801: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 08:17:20,802: INFO: common: created directory at: artifacts]
[2024-05-15 08:17:44,216: INFO: common: json file saved at: scores.json]
[2024-05-15 08:17:44,217: INFO: common: json file saved at: scores.json]
[2024-05-15 08:17:44,217: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-15 09:02:11,424: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 09:02:11,447: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 09:02:11,472: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 09:02:11,524: INFO: common: created directory at: artifacts]
[2024-05-15 09:02:11,530: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 09:02:11,542: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 09:02:32,717: ERROR: main: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C8216059D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))]
Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C8216059D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\anaconda\envs\kidney\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C8216059D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Projects\Kidney_Disease_Classification\main.py", line 12, in <module>
    data_ingestion.main()
  File "e:\Projects\Kidney_Disease_Classification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.download_file()
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "E:\anaconda\envs\kidney\lib\site-packages\gdown\download.py", line 202, in download
    res = sess.get(url, stream=True, verify=verify)
  File "E:\anaconda\envs\kidney\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "E:\anaconda\envs\kidney\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\envs\kidney\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\envs\kidney\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?/export=download&id=1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C8216059D0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
[2024-05-15 09:03:46,196: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 09:03:46,220: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 09:03:46,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 09:03:46,265: INFO: common: created directory at: artifacts]
[2024-05-15 09:03:46,266: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 09:03:46,267: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 09:04:12,855: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 09:04:14,162: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 09:04:14,163: INFO: main: *******************]
[2024-05-15 09:04:14,163: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 09:04:14,166: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 09:04:14,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 09:04:14,168: INFO: common: created directory at: artifacts]
[2024-05-15 09:04:14,169: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 09:04:16,848: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 09:04:17,746: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 09:04:17,746: INFO: main: *******************]
[2024-05-15 09:04:17,746: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 09:04:17,749: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 09:04:17,754: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 09:04:17,756: INFO: common: created directory at: artifacts]
[2024-05-15 09:04:17,757: INFO: common: created directory at: artifacts\training]
[2024-05-15 09:07:21,713: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 09:07:21,714: INFO: main: *******************]
[2024-05-15 09:07:21,714: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 09:07:21,716: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 09:07:21,717: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 09:07:21,718: INFO: common: created directory at: artifacts]
[2024-05-15 09:07:49,036: INFO: common: json file saved at: scores.json]
[2024-05-15 09:07:49,037: INFO: common: json file saved at: scores.json]
[2024-05-15 09:07:49,038: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-15 10:44:12,651: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 10:44:12,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 10:44:12,717: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 10:44:12,739: INFO: common: created directory at: artifacts]
[2024-05-15 10:44:12,742: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 10:44:12,744: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 10:44:39,696: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 10:44:41,977: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 10:44:41,980: INFO: main: *******************]
[2024-05-15 10:44:41,981: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 10:44:41,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 10:44:42,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 10:44:42,016: INFO: common: created directory at: artifacts]
[2024-05-15 10:44:42,018: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 10:44:45,512: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 10:44:47,396: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 10:44:47,400: INFO: main: *******************]
[2024-05-15 10:44:47,402: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 10:44:47,408: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 10:44:47,417: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 10:44:47,421: INFO: common: created directory at: artifacts]
[2024-05-15 10:44:47,487: INFO: common: created directory at: artifacts\training]
[2024-05-15 10:48:26,381: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 10:48:26,389: INFO: main: *******************]
[2024-05-15 10:48:26,390: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 10:48:26,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 10:48:26,458: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 10:48:26,481: INFO: common: created directory at: artifacts]
[2024-05-15 10:49:00,419: INFO: common: json file saved at: scores.json]
[2024-05-15 10:49:00,421: INFO: common: json file saved at: scores.json]
[2024-05-15 10:49:00,422: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-15 12:10:38,527: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-15 12:10:38,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 12:10:38,604: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 12:10:38,632: INFO: common: created directory at: artifacts]
[2024-05-15 12:10:38,633: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-15 12:10:38,634: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 12:11:05,578: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1YhKFP8rX6afx5gPFRux2kSXv9KEs6un7/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-05-15 12:11:08,064: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-05-15 12:11:08,065: INFO: main: *******************]
[2024-05-15 12:11:08,065: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-05-15 12:11:08,070: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 12:11:08,081: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 12:11:08,083: INFO: common: created directory at: artifacts]
[2024-05-15 12:11:08,097: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-05-15 12:11:11,154: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-05-15 12:11:14,000: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-05-15 12:11:14,002: INFO: main: *******************]
[2024-05-15 12:11:14,002: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-05-15 12:11:14,005: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 12:11:14,007: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 12:11:14,008: INFO: common: created directory at: artifacts]
[2024-05-15 12:11:14,009: INFO: common: created directory at: artifacts\training]
[2024-05-15 12:14:52,466: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-05-15 12:14:52,496: INFO: main: *******************]
[2024-05-15 12:14:52,496: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-05-15 12:14:52,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-15 12:14:52,539: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-15 12:14:52,565: INFO: common: created directory at: artifacts]
[2024-05-15 12:15:25,988: INFO: common: json file saved at: scores.json]
[2024-05-15 12:15:25,992: INFO: common: json file saved at: scores.json]
[2024-05-15 12:15:35,084: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-05-15 12:15:36,408: INFO: builder_impl: Assets written to: C:\Users\acer\AppData\Local\Temp\tmp38q038fo\model\data\model\assets]
[2024-05-15 12:16:24,479: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-05-15 12:26:05,545: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.234.98:8080]
[2024-05-15 12:26:05,545: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-15 12:26:44,538: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:26:44] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:26:46,456: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:26:46] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 12:26:55,485: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "e:\Projects\Kidney_Disease_Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-15 12:26:55,642: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:26:55] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-15 12:27:35,733: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:27:35] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:27:37,930: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:27:37] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 12:30:11,001: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "e:\Projects\Kidney_Disease_Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-15 12:30:11,009: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:30:11] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-15 12:32:33,587: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.234.98:8080]
[2024-05-15 12:32:33,589: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-05-15 12:33:14,830: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:33:14] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:33:16,464: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:33:16] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 12:33:39,104: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:33:39] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:33:39,802: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:33:39] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 12:33:48,650: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "e:\Projects\Kidney_Disease_Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-15 12:33:48,655: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:33:48] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-15 12:55:33,251: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:55:33] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:55:34,814: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:55:34] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 12:55:38,466: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\anaconda\envs\kidney\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "E:\anaconda\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "e:\Projects\Kidney_Disease_Classification\app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "e:\projects\kidney_disease_classification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\anaconda\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-05-15 12:55:38,495: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:55:38] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-05-15 12:55:42,836: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:55:42] "GET / HTTP/1.1" 200 -]
[2024-05-15 12:55:43,837: INFO: _internal: 127.0.0.1 - - [15/May/2024 12:55:43] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 19:04:15,967: INFO: _internal: 127.0.0.1 - - [15/May/2024 19:04:15] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 20:34:00,306: INFO: _internal: 127.0.0.1 - - [15/May/2024 20:34:00] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
[2024-05-15 23:16:03,344: INFO: _internal: 127.0.0.1 - - [15/May/2024 23:16:03] "[33mGET /highLightTitle.png HTTP/1.1[0m" 404 -]
